apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /metube/downloads

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: metube-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metube
  template:
    metadata:
      labels:
        app: metube
    spec:
      containers:
      - name: metube
        image: ghcr.io/alexta69/metube
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: downloads-volume
          mountPath: /downloads
      volumes:
      - name: downloads-volume
        persistentVolumeClaim:
          claimName: downloads-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: metube-service
spec:
  type: LoadBalancer
  selector:
    app: metube
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
